name = "majdataplay-distrib"
main = "src/index.js"
compatibility_date = "2024-04-27"

[[r2_buckets]]
binding = "MAJDATA_BUCKET"
bucket_name = "majdataplay-distrib"

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true

