name = "majdataplay-distrib"
main = "src/index.js"
compatibility_date = "2024-04-27"

# 可选：绑定静态资源目录（类似静态网站）
[site]
bucket = "./src/files"

[[r2_buckets]]
binding = "MAJDATA_BUCKET"
bucket_name = "majdataplay-distrib"

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true

